[theme]
primaryColor = "#F47B20"
backgroundColor = "#F7F8FA"
secondaryBackgroundColor = "#FFFFFF"
textColor = "#111827"
font = "sans serif"

[server]
headless = true

[browser]
gatherUsageStats = false
